# Generated by Django 5.2 on 2025-04-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medication',
            old_name='expiry_date',
            new_name='expiration_date',
        ),
        migrations.AddField(
            model_name='medication',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
